title: elliotshabram.com
description: A simple website hosted on github for free.
url: https://elliotshabram.com
author: Elliot Shabram
permalink: /:year/:month/:day/:title/
theme: jekyll-theme-hacker
